name: Generar Diagramas y Docs

on:
  push:
    branches: [ master ] # Cambia a 'master' si es tu rama principal

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Doxygen y Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Ejecutar Doxygen
        run: |
          # Genera un archivo de configuración por defecto si no existe
          doxygen -g 
          # Ajustes para C# y Diagramas
          sed -i 's/OPTIMIZE_OUTPUT_JAVA   = NO/OPTIMIZE_OUTPUT_JAVA   = YES/' Doxyfile
          sed -i 's/HAVE_DOT               = NO/HAVE_DOT               = YES/' Doxyfile
          sed -i 's/UML_LOOK               = NO/UML_LOOK               = YES/' Doxyfile
          sed -i 's/RECURSIVE              = NO/RECURSIVE              = YES/' Doxyfile
          doxygen Doxyfile

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
